#cloud-config
package_update: true

package_upgrade: true

locale: pt_PT

runcmd:
  - yum install -y vim git net-tools
  - useradd -m -d /home/ansiblebot -s /bin/bash ansiblebot
  - echo "ansiblebot:password" | chpasswd
  - mkdir /home/ansiblebot/.ssh
  - touch /home/ansiblebot/.ssh/authorized_keys
  - chown -R ansiblebot:ansiblebot /home/ansiblebot/.ssh
  - chmod 700 /home/ansiblebot/.ssh
  - chmod 600 /home/ansiblebot/.ssh/authorized_keys
  - |
    echo "ansiblebot ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/ansiblebot
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWDAlsCB5kRfoYW1jnd0/9kmZtalmN4cM8T5qJ8ualsMVTwo22ijKwieQG5yRpvgWAb87tBpoTtx+moKk7DIWezkyAAn5ptzHDeupyXith3otLtm8gy6uSvHJWrd3K24pnsjCuHAvlKmqtpC2IiPM0EoHsQLljiOPsSfJ4I8IBCrNMXOZI1tAzTIJB3GIsLk1D6E6/rwSWwqif87mQlqFV2dv3F0qpBN1ZPNldNCor2FD7RWmJsIGmGFadoIW/G/MXDlHn>
  - yum clean all
  - rm -rf /var/cache/yum
